### ISSUE TITLE
registerhyphenationexception does not work

### ISSUE THREAD

**Issue by juh2** [juh2/context-environments#1]
I set this in layout.tex

`\registerhyphenationexception[vo-yeu-ris-tisch zu-sam-men-ge-rauf-ten Ho-nig-a-tem Wüs-ten-a-tem La-bans Lif-shitz]`

But it does not work.

**Comment by ousia** [comment]
I’m investigating what may be the cause. Not found a fix yet, but how does `layout.text` contain the following line?

``` tex
\usemodule[layout]
```

Is the file loading itself?

**Comment by ousia** [comment]
Another question I don’t understand from `layout.tex`:

``` tex
\setuplanguage
    [de-DE]
    [spacing=packed,
    lefthyphenmin=2,
    righthyphenmin=2]
```

If spacing needs to be packed, US English is loaded, not German.

German has packed spacing by default:

``` tex
\startbuffer[points]
\dorecurse{2}{\recurselevel. }
\stopbuffer
\starttext
\getbuffer[points]

\de\getbuffer[points]
\stoptext
```

I think this may be the cause. But I need to examine it further.

**Comment by ousia** [comment]
it works for me with three minor changes:
1. Add `[de]` to `\registerhyphenationexception` (in `layout.tex`).
2. Load `layout.tex` with `\input layout.tex` instead of `\usemodule[layout]` (in the file you load it).
3. Replace `\installlanguage [de-DE] [de-de]` with `\installlanguage [de-DE] [de]` in `pandoc-xhtml`.

I hope it works now.

**Comment by juh2** [comment]
Yes, now it works. Thanks you very much. 

But it seems a little bit strange, that we cannot use 

`\installlanguage [de-CH] [de-de]
`

And are you sure that spacing=packed is loading English? I removed it for now.

**Comment by ousia** [comment]
My explanation wasn’t clear. From `languages-mkiv.pdf`:

> For instance, most languages use the `packed` variant while English, Turkish and Arabic are configured to use `broad`. To some extend you can say that the European continent uses the same spacing setup.

If spacing was broad by default, English was loaded by default (as it is in fact, when no other language is loaded with `\mainlanguage`).

`spacing=packed` doesn’t load any language. But if you require it for German (or any other continental language), it is English the language being used.

And I guess `\installlanguage [de-CH] [de-de]` doesn’t work, because `de-de` is already a language synonym itself. And `de-CH` and `de-DE` are synonyms too.

If there is no bug here (I’m only guessing), it seems that language synonyms cannot come from other language synonyms.
